### ISSUE TITLE
Interaction with board tiles

### ISSUE THREAD

**Issue by bferijan** [se2-monopoly-ss20-v2/monopoly#3]
-     If the player lands on a tile certain interactions need to be possible
-     For example buying land, building houses/hotels, paying money etc.

**Comment by dermutzh** [comment]
Interaction with Deeds is covered in #19. (This contains buying Deeds, buying houses and hotels.)

**Comment by dermutzh** [comment]
Closing this, because it is covered in #47.

**Comment by dermutzh** [comment]
Oops, thought it is only covering Deeds, reopening it.

**Comment by Chfaeser** [comment]
Solved in their respective issues (Special Fields, Deeds, Community Cards)
