### ISSUE TITLE
Handle App Interruptions

### ISSUE THREAD

**Issue by bferijan** [se2-monopoly-ss20-v2/monopoly#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Define how interruptions/terminating of the app will be handled. (E.g. will the player be removed when the App is minimized; or will he only be removed when he terminates the App)

**Comment by dermutzh** [comment]
Will not be implemented.

Reason: 
at current perspective, only focusing on core features of the game. Not really necessary and would blow up the scope of this LV.
